### ISSUE TITLE
libtool check is missing...

### ISSUE THREAD

**Issue by gavenkoa** [cheusov/libmaa#1]
I tried to build `libmaa` in Cygwin with some package missing.

`./configure` create `Makefile` with empty:

    LIBTOOL=	

so I have error:

    $ make SHELL='sh -x'

    tag=CC --mode=compile gcc -o obstack.o -c -DHAVE_CONFIG_H  -Wall -Werror -g -O2 -DMAA_MAJOR=1 -DMAA_MINOR=3 -DMAA_TEENY=2 -I. -I. obstack.c
    + tag=CC
    + --mode=compile gcc -o obstack.o -c -DHAVE_CONFIG_H -Wall -Werror -g -O2 -DMAA_MAJOR=1 -DMAA_MINOR=3 -DMAA_TEENY=2 -I. -I. obstack.c
    sh: --mode=compile: command not found
    make: [Makefile:115: obstack.o] Error 127 (ignored)

`LT_PREREQ` macro can help detect such issue: https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html

**Comment by gavenkoa** [comment]
Also `./configure` doesn't detect absence of `yacc`.

**Comment by cheusov** [comment]
LT_PREREQ -- should be fixed now. Please check.

**Comment by gavenkoa** [comment]
git log --graph --oneline --decorate
    * 5b25c17 (HEAD -> master, origin/master, origin/HEAD) Add LT_PREREQ macros to autoconf.ac
    * ed3f616 fix in doc/Makefile.in
    * f82d2f3 configure.in renamed to configure.ac
    * 20fdb22 configure.in was updated with a help of autoupdate
    * 4922262 (grafted) License has been changed from LGPL to MIT, permitted by Rik Faith.

    bash# autoreconf-2.69

    bash# ./configure 
    ./configure: line 2346: syntax error near unexpected token `2.4.2'
    ./configure: line 2346: `LT_PREREQ(2.4.2)'

**Comment by gavenkoa** [comment]
I've built `libmaa` on old sources `4922262` after figuring out what packages are missing (I had fresh minimal Cygwin installation).

I've built `dictd` (I need `dictfmt` utility) with minor editing of `Makefile` in order to provide direct path to `libmaa.a` and `.h` instead of `-lmaa` and for `-I` for preprocessor.

**Comment by gavenkoa** [comment]
bash# apt-cyg install libtool
    bash# autoreconf

    bash# ./configure --prefix=$HOME/usr
    ./configure: line 2346: syntax error near unexpected token `2.4.2'
    ./configure: line 2346: `LT_PREREQ(2.4.2)'

Commenting :

     dnl LT_PREREQ([2.4.2])

allows to complete configure.

**Comment by cheusov** [comment]
I don't use autocrap anymore. So, this issue is no longer an issue.
