### ISSUE TITLE
Buildsystem is not parallel-safe

### ISSUE THREAD

**Issue by mistydemeo** [cheusov/libmaa#2]
With `MAKEFLAGS` set to pass parallel arguments, such as `-j4`, the buildsystem may try to compile `arg.c` before the generated `arggram.c` file it depends on has been created.  Here's sample failed build output:

```
--- arg.os ---
arg.c:203:10: fatal error: 'arggram.c' file not found
#include "arggram.c"
         ^~~~~~~~~~~
1 error generated.
*** [arg.os] Error code 1
```

Steps to reproduce:

1. `export MAKEFLAGS=-j4`
2. `mkcmake`

**Comment by cheusov** [comment]
@mistydemeo Build itself is threadsafe. However, "errorcheck" phase is not. Try the following.
mkcmake errorcheck
mkcmake -j4 all

**Comment by mistydemeo** [comment]
That still fails, unfortunately, with the same error. It looks like it's not just errorcheck that is parallel-unsafe.

**Comment by cheusov** [comment]
@mistydemeo Did you run exactly the command I specified above?
 Before running "mkcmake errocheck", do not forget to unset MAKEFLAGS.

**Comment by cheusov** [comment]
@mistydemeo Ah! I understand! I already fixed the problem immediately after releasing 1.4.2, See commit 3f91ed0c3c765ef3fae2b1aa64eaa79e2123a41a

**Comment by mistydemeo** [comment]
Aha! Can confirm, it works on master.
