### ISSUE TITLE
Makefile:5: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by amaccis** [cheusov/libmaa#4]
Hi.
I'm having compilation troubles. 
When I run make, I get Makefile:5: *** missing separator.  Stop.
I'm on alpine 3.10.
What am I doing wrong?
Thanks!

**Comment by cheusov** [comment]
Perhaps, you are trying to use GNU make, which is the default for almost all Linux distributions. You need mk-configure for building libmaa. You can find mk-configure on my github, and it is based on bmake, NetBSD variant of make utility.
